export const LOCATION = [
  { name: '서울시', id: '1' },
  { name: '인천시', id: '2' },
  { name: '대전시', id: '3' },
  { name: '대구시', id: '4' },
  { name: '광주시', id: '5' },
  { name: '부산시', id: '6' },
  { name: '울산시', id: '7' },
  { name: '세종시', id: '8' },
  { name: '경기도', id: '31' },
  { name: '강원도', id: '32' },
  { name: '충청북도', id: '33' },
  { name: '충청남도', id: '34' },
  { name: '경상북도', id: '35' },
  { name: '경상남도', id: '36' },
  { name: '전라북도', id: '37' },
  { name: '전라남도', id: '38' },
  { name: '제주도', id: '39' },
];
