export const LOCATION = [
  { name: '서울시', num: 1 },
  { name: '인천시', num: 2 },
  { name: '대전시', num: 3 },
  { name: '대구시', num: 4 },
  { name: '광주시', num: 5 },
  { name: '부산시', num: 6 },
  { name: '울산시', num: 7 },
  { name: '세종시', num: 8 },
  { name: '경기도', num: 31 },
  { name: '강원도', num: 32 },
  { name: '충천북도', num: 33 },
  { name: '충천남도', num: 34 },
  { name: '경상북도', num: 35 },
  { name: '경상남도', num: 36 },
  { name: '전라북도', num: 37 },
  { name: '전라남도', num: 38 },
  { name: '제주도', num: 39 },
];
